from nerfstudio.plugins.registry_dataparser import DataParserSpecification
from triplane.triplane_dataparser import MipBlenderDataParserConfig

blender_mip_dataparser = DataParserSpecification(config=MipBlenderDataParserConfig())
